### ISSUE TITLE
Use pseudo-patterns as pattern partials

### ISSUE THREAD

**Issue by aleksip** [pattern-lab/patternlab-php-core#23]
This would be a nice feature to have! The documentation is quite strongly worded that it is not possible. Is this a philosophical thing or just due to the current technical implementation?

**Comment by dmolsen** [comment]
It's a philosophical decision that has affected the tech implementation. The primary issue is one of data inheritance. Right now, the top-level pattern data overrides the global data. That keeps things simple and I don't have to worry about any sort of lineage/data bubbling. It kills pseudo-patterns as anything but a way to show variations of a pattern. That said, it's come up as a desired feature and it can be implemented as a plug-in. I prefer it as a plug-in because that makes it opt-in since it would be a big break from the past.

I think it could really easily be inserted as a "helper." After pattern data is loaded via the rules PL2 works through "helpers" and "exporters." Helpers are functionality that loops through the pattern data and modifies it. An example would be lineage. Exporters take that data and, well, export it if appropriate. They export to disk as JSON (e.g. nav items) or to static stores in other classes (e.g. `Data`). Once the `patternData.lineageHelperEnd` event runs the helper could easily loop over the pattern data store and merge pattern-specific data as appropriate up the pattern chain as it were. I don't think it'd even be that much of a processor hog.

Doing this would both elevate pseudo-patterns to first-class pattern partials but it'd also mean any sort of data stored with a pattern could bubble up to affect items further up the pattern chain.

**Comment by aleksip** [comment]
Thanks for the answer! I might look into implementing this in `plugin-data-transform`.

**Comment by dmolsen** [comment]
If it's possible to create a separate plugin please do but I understand if it doesn't fit the Drupal workflow.
