### ISSUE TITLE
Support `.yml` extension in addition to `.yaml`

### ISSUE THREAD

**Issue by EvanLovely** [pattern-lab/patternlab-php-core#25]
It's great that data files can take the form of `pattern.yaml`, but many people use it as `pattern.yml` – even Pattern Lab's own `config/config.yml`! This can be a subtle difference and could easily add some confusion for users.

**Comment by dmolsen** [comment]
Easy enough to fix. References in pattern rules should be `json||yaml||yml` instead of `json||yaml`. See [PatternInfoRule.php](https://github.com/pattern-lab/patternlab-php-core/blob/25c71af708d996d1e2b09490b380b3418918d58f/src/PatternLab/PatternData/Rules/PatternInfoRule.php#L29) as an example. I'll get to this late next week unless you get to this first. Finishing up #14 is my priority at the moment.
