### ISSUE TITLE
Shorthand syntax for includes

### ISSUE THREAD

**Issue by hctom** [pattern-lab/patternlab-php-core#55]
I just wondered if the shorthand partials syntax for ```{% include %}``` only works in the format ```TYPE-TPLNAMEWITHOUTEXT```?

We are running into problems with this, because we have templates saved like this (to keep the patternlab menu links as short as possible):

- atoms
  - component
    - default.twig
    - xyz.twig
  - another-component
    - default.twig

As you can see, shorthand syntax ```atoms-default``` would target two different templates. So is this by design (I know templates should normally have the component name as filename), or is there any possibility to target an exact component, even if there is another one with the same template name?

Or on the other hand: Is there any possibility to control the menu link title in the patternlab menu?

Thanx in advance

(This is a follow up to https://github.com/aleksip/plugin-data-transform/issues/4, where we stumbled upon this problem when using the ```include()``` function provided by the plugin).

**Comment by dmolsen** [comment]
@hctom -

There's a little bit to unpack here so if I don't quite answer your question please let me know.

1. That's a known issue with the shorthand syntax. It was always meant to be a shortcut but you can use the regular Twig include syntax if you want. You should be able to use `{% include "atoms/components/default" %}` if you need to target something specifically from within a template. You'll have to add the numbering and all that junk if you have it. Nav may be borked though.
2. To replace a name you could add `default.md` and set it like:

```yaml
---
title: New title
---
A markdown description of the pattern.
```

Looks like there's a bug in the title replacement code. Core was set to be updated tonight anyway so that will be fixed in `v2.5.0`. As long as the `.md` file name matches the `.twig` file you should be good to go.

**Comment by hctom** [comment]
Thanx for the detailed answer. This helps a lot. Of course I knew the "normal" include syntax, but this would have lead to the quite long menu item links. But with the *.md file hint, we will fix that. I'll give the update a try, but I saw there is the new base path config, I have to fiddle a little around with, so it will still work in our Drupal theme, where the base path varies ;)

I close this issue, because all of my questions were answered.

Thanx a lot!

**Comment by dmolsen** [comment]
Welcome :)
